---
title: "Instrumental Phonetics 2020"
---

[Here](https://www.hse.ru/data/2018/01/26/1162932180/program-1719609140-3tWrq6PIZD.pdf) is a link to a course programme.

Final Mark =0.6 $\times$ (HW) + 0.4 $\times$ (Exam)

### 1. Introduction to Acoustic Phonetics

* (16.01.2020)	[Lec 1](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/20.01.16_Acoustic_Phonetics_lec_1.pdf), [additional materials on waves](https://pudding.cool/2018/02/waveforms/)
* (16.01.2020)	Lab 1: [Praat](http://www.fon.hum.uva.nl/praat/). Symbols for [consonats](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__consonants_1.png), [vowels](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__vowels_1.png) and [diacritics](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__diacritics.html)
* HW 1 (23.01.2020) I'll send you a chapter from some hadbook on articulation and sounds types. We will have a little test on it.
* HW 2 (due to 30.01.2020): 
    * Create the  annotation for [this sound file](https://github.com/agricolamz/2018_m_Instrumental_Phonetics/blob/master/docs/materials/andi_plosives.wav?raw=true) containing words *bek':ub* (hot), *wuk:udu* (fall down), *tʃ'ek'a* (foot) and *t'uka* (goat). Here is [an example](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/hw1.png).
    * Send the `.TextGrid` file to the course assistant [Sasha Shiryayev](mailto:ashiryaev87@gmail.com) with the topic `Instrumental Phonetics: HW 1`

### 2. Vowels. Formants

* (30.01.2020)	[Lec 2](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/18.02.10_Vowels.pdf)
* [sound](https://goo.gl/IzpUyo)
* [TextGrid](https://goo.gl/4tGthZ)
* [extracted formant values](https://goo.gl/zPm7Od)
* [Lennes M. (2002) Calculate segment durations](https://lennes.github.io/spect/scripts/calculate_segment_durations.praat)
* [Kawahara (??) Extract formant chart](https://goo.gl/MUBpPw)
* [R script for the visualisation of duration](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/materials/plot_duration.R)

### 3. Reading spectrum

* (06.02.2020)	[Lec 3](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/20.02.13_Reading_spectrograms.pdf)

### 4. Reading spectrum

* (27.02.2020)	Lec 4

### 5. Sonorants

* (05.03.2020)	[Lec 5](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/2020.03.06_Sonorants.pdf)
* (05.03.2020)	[Lab 5](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/18.02.17_Sonorants_sem_3.pdf)
* [Andi nasals](https://goo.gl/5D9DNR)

### 6. Obstruents

* (12.03.2020)	[Lec 6](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/20.03.12_Obstruents_lec_4.pdf)
* (12.03.2020)	[Lab 6](https://github.com/agricolamz/2020_HSE_m_Instrumental_phonetics/raw/master/docs/18.02.24_Obstruents_sem_4.pdf)
* [fricatives](https://goo.gl/hvdviI), [fricatives' TextGrid](https://goo.gl/pza6tx), Extracted data: [ɬ](https://goo.gl/wo3QZN), [s](https://goo.gl/eNZQKa), [sh](https://goo.gl/NgeVSX), [x](https://goo.gl/oDYvbJ), [χ](https://goo.gl/vZQfZG) 
* [fricatives' R script](https://goo.gl/SdGlZr)

* [plosives](https://goo.gl/PZA8WY), [plosives' TextGrid](https://goo.gl/1ZFtJt), Extracted data: [plosives' duration](https://goo.gl/NExChs)
* [plosives' R script](https://gist.githubusercontent.com/agricolamz/c4c5e6dfd5cfcd8052e5f03db7b12f64/raw/54248887fef342aad90db42f5439456dda5f1d88/CD_VOT.R)

* HW 3 (due to 26.03.2020): 
    * watch all videos about palatography (they will be in the exam) [1st](https://www.youtube.com/watch?v=wCDuh6dfw6g&index=1&list=PL1741BF0646F7DEEF), [2nd](https://www.youtube.com/watch?v=2XEJVs6XbYA&index=2&list=PL1741BF0646F7DEEF), [3rd](https://www.youtube.com/watch?v=kC1x63lgulM&list=PL1741BF0646F7DEEF&index=3), [4th](https://www.youtube.com/watch?v=llP36cePiMM&list=PL1741BF0646F7DEEF&index=4), [5th](https://www.youtube.com/watch?v=CqN-mh02o5U&list=PL1741BF0646F7DEEF&index=5), [6th](https://www.youtube.com/watch?v=8Sh5hFnIuS4&index=6&list=PL1741BF0646F7DEEF)

* HW 4 (due to 26.03.2020):
    * Download [the sound](https://github.com/agricolamz/2018_m_Instrumental_Phonetics/blob/master/docs/materials/mehweb_dental_stops_affricates.wav?raw=true) and the [TextGrid file](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/materials/mehweb_dental_stops_affricates.TextGrid)
    * Annotate CD and VOT
    * Create three pictures with R that we discussed in class (example: [pic 1](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/hw2_1.jpeg), [pic 2](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/hw2_2.jpeg), [pic 3](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/hw2_3.jpeg))
    * Write a short text analysing results: what is the difference in CD and VOT values between stops and affricates, ejectives and non-ejectives?
      * Send the `.TextGrid` file, pics and text to the course assistant [Sasha Shiryayev](mailto:ashiryaev87@gmail.com) with the topic `Instrumental Phonetics: HW 2`

### 7. Perception

* (19.03.2020) Lec 8


### EXAM
  
### Useful links

* [Interactive tutorials on waves](https://pudding.cool/2018/02/waveforms/)
* [the real-time MRI IPA charts](http://sail.usc.edu/span/rtmri_ipa/index.html)

### Reference:

* Ashby, M., J. Maidment (2005). Introducing phonetic science. Cambridge University Press.
* Bickford, A. C., R. Floyd (2006). Articulatory Phonetics: Tools for Analyzing the World’s Languages SIL International. 
* Boersma,  P.,  D.  Weenink  (2013). Praat:    doing  phonetics  by  computer  (version 5.3.51)[computer program]. retrieved 2 june 2013.
* Fant, G. (1971). Acoustic theory of speech production:  with calculations based on X-ray studies of Russian articulations, Volume 2.  Walter de Gruyter.
* Fuchs, S., M. Toda„ M. Żygis (2010). Turbulent sounds:  an interdisciplinary guide, Volume 21.  Walter de Gruyter.
* Fulop, S. (2011). Speech spectrum analysis.  Springer Science & Business Media.
* Gick, B., I. Wilson D. Derrick (2012). Articulatory phonetics. John Wiley & Sons.
* Gordon, M., P. Ladefoged (2001).  Phonation types: a cross-linguistic overview. Journal of Phonetics 29 (4), 383–406.
* Harrington, J. (2010). Phonetic analysis of speech corpora. John Wiley & Sons.
* [Hon Hunt, E. (2009). Acoustic Characterization of the Glides /j/ and /w/ in American English](https://dspace.mit.edu/bitstream/handle/1721.1/52797/547382338-MIT.pdf;sequence=2)
* Johnson, K. (2011). Acoustic and auditory phonetics. John Wiley & Sons.
* Ladefoged, P., S. F. Disner (2012). Vowels and consonants. John Wiley & Sons.
Ladefoged, P., I. Maddieson. (1996). The Sounds of the World’s Languages Oxford, Cambridge: Blackwell Publishers.
* Rorabaugh, C. B. (2010). Notes on Digital Signal Processing: Practical Recipes for Design, Analysis and Implementation Prentice Hall